# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

source 'https://gitee.com/xiu_ce/MainModule.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'XCFMStudio' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'MainModule'
  # Pods for XCFMStudio

end
