# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

source 'https://gitee.com/Alexiuce/XCApplicationModuleKit.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'CallDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for CallDemo
pod 'MJExtension'
pod 'XCSqliteKit'
end
