# Uncomment the next line to define a global platform for your project
 platform :osx, '10.11'

target 'iFeiBo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iFeiBo

  pod 'pop'
  pod 'Alamofire', '~> 4.5'
  pod 'MJExtension'
  pod 'Kingfisher', '3.13.1'


end
