# Uncomment the next line to define a global platform for your project
 platform :osx, '10.11'

target 'XCRefresh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCRefresh
   pod 'Aspects'
end
