# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AVFoundationDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVFoundationDemo

end

target 'BaiduMap Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BaiduMapKit'

end

target 'Core Image Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Core Image Demo

end

target 'Tip for Day Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tip for Day Demo

end

target 'XCPhotoEditPicker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCPhotoEditPicker

end


target 'GitHubApiDemo' do
     platform :osx, '10.12'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'Kingfisher', '~> 3.0'

    
end
target 'OpenCV Demo' do
   
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    #use_frameworks!
  
    
    
end

target 'RxSwiftDemo' do
    
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    
end

target 'ReamAndChartsDemo' do
    
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Charts', '~> 3.0.1'
    pod 'RealmSwift', '~> 2.0.2'
    
end

