# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AVFoundationDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVFoundationDemo

end

target 'BaiduMap Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BaiduMapKit'

end

target 'Core Image Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Core Image Demo

end

target 'Tip for Day Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tip for Day Demo

end

target 'XCPhotoEditPicker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCPhotoEditPicker

end
