# Uncomment the next line to define a global platform for your project
 platform :osx, '10.10'

target 'AnimationDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimationDemo
  pod 'pop', '~> 1.0'

end
